version: '3.3'
services:
  db:
    image: library/mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: IKhVvZVl0yZLgD3
      MYSQL_DATABASE: bot_database
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: