version: '3.3'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: IKhVvZVl0yZLgD3
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - postgres:/data/postgres
volumes:
  postgres: